version: '3.8'

services:
  backend:
    build: ./s3-upload-backend
    ports:
      - "3001:3001"
    env_file:
      - ./s3-upload-backend/.env
    environment:
      - PORT=3001

  frontend:
    build: ./s3-upload-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
